<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-32GN0UI0" failures="2" tests="4" name="Test" time="15.712" errors="0" timestamp="23 Nov 2022 14:01:14 GMT">
  <testcase classname="test.PhpTravels.AppTest" name="testAppTest" time="3.455"/>
  <testcase classname="test.PhpTravels.SeleTest" name="testAppTest" time="1.07"/>
  <testcase classname="test.PhpTravels.SeleTest" name="testIrctc" time="4.019">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testIrctc() didn&amp;apos;t finish within the time-out 4000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testIrctc() didn't finish within the time-out 4000
	at java.base@17.0.4.1/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base@17.0.4.1/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base@17.0.4.1/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base@17.0.4.1/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base@17.0.4.1/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base@17.0.4.1/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base@17.0.4.1/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base@17.0.4.1/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base@17.0.4.1/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at app//org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:144)
	at app//org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
	at app//org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:310)
	at app//org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.to(RemoteWebDriver.java:981)
	at app//test.PhpTravels.SeleTest.testIrctc(SeleTest.java:42)
	at java.base@17.0.4.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base@17.0.4.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- testIrctc -->
  <testcase classname="test.PhpTravels.SeleTest" name="testSeleTest" time="7.018">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at test.PhpTravels.SeleTest.testSeleTest(SeleTest.java:33)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testSeleTest -->
</testsuite> <!-- Test -->
